# Generated by Django 5.0.1 on 2024-01-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xác nhận'), (2, 'Đang chờ thanh toán'), (3, 'Đang vận chuyển'), (4, 'Đã giao hàng'), (5, 'Chờ huỷ'), (6, 'Đã huỷ')], default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='confirmation_status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xác nhận'), (2, 'Đang chờ thanh toán'), (3, 'Đang vận chuyển'), (4, 'Đã giao hàng'), (5, 'Chờ huỷ'), (6, 'Đã huỷ')], default=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xác nhận'), (2, 'Đang chờ thanh toán'), (3, 'Đang vận chuyển'), (4, 'Đã giao hàng'), (5, 'Chờ huỷ'), (6, 'Đã huỷ')], default=1),
        ),
    ]
