# Generated by Django 4.2.7 on 2023-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart_cartitem_orderitem_post_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='zone',
            field=models.CharField(choices=[('HCM', 'Hồ Chí Minh'), ('DN', 'Đà Nẵng'), ('HN', 'Hà Nội'), ('UN', '')], default='UN', max_length=4),
        ),
    ]
