# Generated by Django 5.0.1 on 2024-01-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_name_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_without_accent',
            field=models.CharField(blank=True, null=True),
        ),
    ]
