# Generated by Django 5.0 on 2024-01-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_fieldoptions_fieldoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoption',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
