# Generated by Django 5.0 on 2024-01-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_fieldoption_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldoption',
            name='field_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.field'),
        ),
    ]
