# Generated by Django 5.0 on 2024-01-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_fieldoption_field_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
