# Generated by Django 5.0 on 2024-01-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
