# Generated by Django 5.0 on 2024-01-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_product_attachments_attachment_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_urls',
        ),
    ]
