# Generated by Django 5.0 on 2024-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_fieldvalue_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'INPUT'), (2, ' SELECT'), (3, 'MULTISELECT')], default=1),
        ),
    ]
