# Generated by Django 5.0 on 2024-01-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_post_price_alter_field_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldoption',
            name='value',
        ),
    ]
