# Generated by Django 5.0 on 2024-01-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_fieldoption_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='fieldoption',
            old_name='field_id',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='field_id',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='fieldvalue',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer_id',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
