# Generated by Django 5.0 on 2024-01-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fieldvalue',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='field_values',
            field=models.ManyToManyField(to='store.fieldvalue'),
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(blank=True, to='store.field'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='field_values',
            field=models.ManyToManyField(to='store.fieldvalue'),
        ),
    ]
