# Generated by Django 5.0 on 2024-01-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_field_category_remove_fieldvalue_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='field_values',
        ),
        migrations.RemoveField(
            model_name='category',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='field_values',
        ),
        migrations.AddField(
            model_name='field',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='store.category'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.CharField(max_length=255, verbose_name='Attachment URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zone',
            field=models.CharField(choices=[('HCM', 'TP. Hồ Chí Minh'), ('DN', 'Đà Nẵng'), ('HN', 'Hà Nội'), ('CT', 'Cần Thơ'), ('HP', 'Hải Phòng')], default='HCM', max_length=4),
        ),
    ]
