# Generated by Django 5.0.1 on 2024-01-05 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_phone_order_phone_number_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xác nhận'), (2, ' Chưa thanh toán'), (3, 'Đã thanh toán'), (4, 'Đang vận chuyển'), (5, 'Đã giao hàng'), (0, 'Đã huỷ')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 14, 47, 39, 272064)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đang chờ xác nhận'), (2, ' Chưa thanh toán'), (3, 'Đã thanh toán'), (4, 'Đang vận chuyển'), (5, 'Đã giao hàng'), (0, 'Đã huỷ')], default=1),
        ),
    ]
