from django.contrib import admin
from . models import Category, User, Product, Order, OrderItem, Cart, CartItem, Transaction, Post, Field, FieldOption, Attachment, FieldValue
admin.site.register(Category)
admin.site.register(User)
admin.site.register(Product)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Cart)
admin.site.register(CartItem)
admin.site.register(Transaction)
admin.site.register(Post)
admin.site.register(Field)
admin.site.register(FieldOption)
admin.site.register(Attachment)
admin.site.register(FieldValue)